cloud:
  aws:
    credentials:
      access-key: ${aws-access-key}
      secret-key: ${aws-secret-key}
    s3:
      bucket: entry-mini
    stack:
      auto: false
    region:
      static: ap-northeast-2

aws:
  s3:
   url: https://entry-mini.s3.ap-northeast-2.amazonaws.com
   bucket: entry-mini
   blog-folder: blogFolder


spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

    url: jdbc:mysql://localhost:3306/s3
    username: root
    password: 1234
  #
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update



