cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID}
      secret-key: ${AWS_SECRET_ACCESS_KEY}
    s3:
      bucket: entry-mini
    stack:
      auto: false
    region:
      static: ${AWS_REGION}

aws:
  s3:
   url: https://entry-mini.s3.ap-northeast-2.amazonaws.com/
   bucket: entry-mini
   blog-folder: blogFolder


jackson:
  property-naming-strategy: SNAKE_CASE


spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

    url: jdbc:mysql://localhost:3306/s3
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  #
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update



